version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - testpackage
    - wrapcheck
    - wsl

  settings:
    ireturn:
      allow:
        - empty
        - error
        - generic
        - Obfuscator
    lll:
      line-length: 180
    paralleltest:
      ignore-missing: true
    revive:
      rules:
        - name: package-comments
          disabled: true
    varnamelen:
      ignore-decls:
        - i int
        - s string
        - m map[string]string
        - m map[string][]string
        - o Obfuscator

  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - funlen
          - goconst
      - path: '(.+)/examples_test\.go'
        linters:
          - depguard

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
